### ISSUE TITLE
interface emits foreign signals

### ISSUE THREAD

**Issue by smoebody** [Shouqun/node-dbus#151]
hi, 

im building a tool which utilizes the mpris-interface of mediaplayers. when i connect to a service and listen to its signals i also get notified by the same signals of a different service. 
For example i connect to the service 'spotify':
```javascript
let DBus = require('dbus');
let dbus = new DBus();
bus.getInterface('org.mpris.MediaPlayer2.spotify', '/org/mpris/MediaPlayer2', 'org.freedesktop.DBus.Properties', (err, iface) => {
  console.log(iface.serviceName);   // "org.mpris.MediaPlayer2.spotify"
  console.log(iface.objectPath);    // "/org/mpris/MediaPlayer2"
  console.log(iface.interfaceName); // "org.freedesktop.DBus.Properties"
  iface.on('PropertiesChanged', (ifaceName, value) => {
    // here i get changes from other services as well
  });
});
```

But i when i start a second player which is mpris-enabled, lets say 'rhythmbox' i get the players 'PropertiesChanged' signal as well. Since i connected to a specific services interface i expect to get only the services signals.

any ideas?

cheers
smoe

**Comment by bryanburgers** [comment]
I can confirm that I was able to reproduce this with a simplified test case.

```
$ SERVICE=issue.signals.Service1 node server &
$ SERVICE=issue.signals.Service2 node server &
$ node listener
issue.signals.Service1:issue.signals.Interface1
issue.signals.Service2:issue.signals.Interface1
issue.signals.Service1:issue.signals.Interface1
issue.signals.Service2:issue.signals.Interface1
issue.signals.Service1:issue.signals.Interface1
issue.signals.Service2:issue.signals.Interface1
^C
```

So, like you said, it looks like the listener is accepting messages from the wrong service when it shouldn't be.

However, the listener is only accepting messages from the correct interface (because the line `issue.signals.Service1:issue.signals.Interface2` never shows up).

<details>
  <summary>server.js</summary>

```js
if (!process.env.SERVICE) {
        console.log('usage: SERVICE=issue.signals.Service1 node service');
        process.exit(1);
}
const serviceName = process.env.SERVICE;

const DBus = require('dbus');
const service = DBus.registerService('session', serviceName);
const obj = service.createObject('/issue/signals');

// Create the first interface to emit on.
const iface1 = obj.createInterface('issue.signals.Interface1');
iface1.addSignal('Message', { types: [DBus.Define(String)] });
iface1.update();

// Create a second interface, to see if the listener is
// getting messages from the wrong interface.
const iface2 = obj.createInterface('issue.signals.Interface2');
iface2.addSignal('Message', { types: [DBus.Define(String)] });
iface2.update();

// Emit messages from both interfaces every 1s.
setTimeout(() => {
        setInterval(() => {
                iface1.emitSignal('Message', `${serviceName}:issue.signals.Interface1`);
        }, 1000);
}, 500);

setInterval(() => {
        iface2.emitSignal('Message', `${serviceName}:issue.signals.Interface2`);
}, 1000);
```

</details>

<details>
  <summary>listener.js</summary>

```js
const DBus = require('dbus');
const bus = DBus.getBus('session');

bus.getInterface('issue.signals.Service1', '/issue/signals', 'issue.signals.Interface1', (err, iface) => {
        if (err) {
                console.log(err);
                bus.disconnect();
        }

        iface.on('Message', msg => {
                console.log(msg);
        });
});
```

</details>

**Comment by bryanburgers** [comment]
@Shouqun This seems to be related to the fact that `Bus.prototype.addSignalFilter` adds a signal filter for **ALL SIGNALS**. [lib/bus.js line 221](https://github.com/Shouqun/node-dbus/blob/master/lib/bus.js#L221)

If I change that filter instead to the following so that we're just listening for `DBus.Local`'s `Disconnected` signal:

```js
self._dbus.addSignalFilter(self.connection, 'type=\'signal\',sender=\'org.freedesktop.DBus\',interface=\'org.freedesktop.DBus.Local\',path=\'/org/freedesktop/DBus/Local\'');
```

it seems to work as expected.

Two questions, then:

1) Is there a reason that the signal filter is added for **ALL** signals?
2) Should we always be listening for `DBus.Local`'s `Disconnected` event? It looks like it only gets added once the client code starts listening for any other signal.

**Comment by bryanburgers** [comment]
Maybe related, maybe not: I don't get *any* events if I connect to another bus via `const bus2 = DBus.getBus('session');` anywhere in my code.

**Comment by Shouqun** [comment]
@bryanburgers for question #1, I remember  the reason was to add ALL signals first  and then filter the  specific one (though which may have performance issue.), looks like this was break later.
